#!/bin/sh
# $Id$

. ./Maintainer/tools.sh

CFLAGS=`cat config.mk | grep CFLAGS | sed "s/CFLAGS = *//g" | grep -oE -- "-D[^ ]+" | sed 's/\\\\//g'`
ERRORS=0
for i in $DIRS; do
	echo "--- $i"
	for j in `list $i`; do
		echo "----- $j"
		lint -X 233,265,236 -Ppnus -D__inline= -Drestrict= -D__attribute__\(x\)= $CFLAGS  $j
		if [ ! "$?" = "0" ]; then
			ERRORS=$(($ERRORS + 1))
		fi
	done
done
echo
echo "$ERRORS error(s)"
if [ "$ERRORS" -gt 0 ]; then
	exit 1
fi
