#!/bin/sh
# $Id$

. ./Maintainer/tools.sh

ERRORS=0
for i in $DIRS; do
	echo "--- $i"
	for j in `list $i`; do
		echo "----- $j"
		lint -X 49,233,234,236,265,272 -DPREFIX='"/usr/local"' -DNEWSDIST_VERSION='"lint"' -Ppnus -D_Noreturn= -D__inline= -Drestrict= -D__attribute__\(x\)= -Dinline= $CFLAGS  $j
		if [ ! "$?" = "0" ]; then
			ERRORS=$(($ERRORS + 1))
		fi
	done
done
echo
echo "$ERRORS error(s)"
if [ "$ERRORS" -gt 0 ]; then
	exit 1
fi
