#!/bin/sh
# $Id$

if [ "x$PREFIX" = "x" ]; then
	PREFIX="/usr/local"
fi
VERSION="1.0"

stty -echo

if [ ! "x$1" = "x" ]; then
	. "$1"
fi

PRINTF="printf"

OLDIFS="$IFS"
IFS=":"

for i in $PATH; do
	if [ -f $i/printf ]; then
		PRINTF=$i/printf
		break
	fi
done

IFS="$OLDIFS"

input=""

$PRINTF "\x1b[m"

error_raw () {
	$PRINTF "\x1b[1m\x1b[31m!!!\x1b[m $1"
}

warn_raw () {
	$PRINTF "\x1b[1m\x1b[33m!!!\x1b[m $1"
}

info_raw () {
	$PRINTF "\x1b[1m\x1b[37m???\x1b[m $1"
}

log_raw () {
	$PRINTF "\x1b[1m\x1b[37m   \x1b[m $1"
}

error () {
	error_raw "$1\n"
}

warn () {
	warn_raw "$1\n"
}

info () {
	info_raw "$1\n"
}

log () {
	log_raw "$1\n"
}

quit () {
	log ""
	error 'Configuration aborted.'
	rm -f config.h
	rm -f config.mk
	stty echo
	exit 1
}

getinput () {
	default="$2"
	while true; do
		if [ "x$2" = "x" ]; then
			$PRINTF "\x1b[1m\x1b[34m???\x1b[m $1? "
		else
			$PRINTF "\x1b[1m\x1b[34m???\x1b[m $1 [$default]? "
		fi
		stty echo
		read input || quit
		stty -echo
		if [ "x$input" = "x" -a "x$default" = "x" ]; then
			error "There is no default value"
		elif [ "x$input" = "x" -a ! "x$default" = "x" ]; then
			input="$default"
			break
		elif [ ! "x$input" = "x" ]; then
			break
		fi
	done
}

test_c () {
	result=0
	rm -f /tmp/$$.c
	$PRINTF "$1" > /tmp/$$.c
	if [ "x$2" = "x" ]; then
		$CC $CFLAGS -Werror -c -o /tmp/$$.o /tmp/$$.c >/dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "yes"
		else
			echo "no"
			result=1
		fi
		rm -f /tmp/$$.c /tmp/$$.o
	else
		$CC $CFLAGS $LDFLAGS -Werror -o /tmp/$$ /tmp/$$.c $2 >/dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "yes"
		else
			echo "no"
			result=1
		fi
		rm -f /tmp/$$.c /tmp/$$
	fi
	return $result
}

DEFINES=""

define () {
	if [ "x$DEFINES" = "x" ]; then
		DEFINES="\"$1\""
	else
		DEFINES="$DEFINES,\"$1\""
	fi
	echo "#define $1" >> config.h
}

trap quit 2

log ""
log "Welcome to NewsDist build environment configuration utility."
log "NewsDist is a small (enough) NNTP server."
log "         is under public-domain."
log ""

if [ "x$CC" = "x" ]; then
	getinput "What is your C compiler" "cc"
	CC="$input"
fi

while [ ! "x$WINSOCK" = "xno" -a ! "x$WINSOCK" = "xyes" -a ! "x$WINSOCK" = "xn" -a ! "x$WINSOCK" = "xy" ]; do
	getinput "Do you need WinSock" "n"
	WINSOCK="`echo "$input" | tr '[:upper:]' '[:lower:]'`"
done

if [ "x$WINSOCK" = "xyes" ]; then
	WINSOCK="y"
elif [ "x$WINSOCK" = "xno" ]; then
	WINSOCK="n"
fi

echo "/* This file is auto-generated */" > config.h
echo "#ifndef __NEWSDIST_CONFIG_H__" >> config.h
echo "#define __NEWSDIST_CONFIG_H__" >> config.h

if [ "$WINSOCK" = "y" ]; then
	LIBS="$LIBS -lws2_32"
	EXEC=".exe"
	log "Guessing this is Windows build"
	define "USE_WINSOCK"
	log_raw "Checking if select exists: "
	test_c "#include <winsock2.h>\nint main(int argc, char** argv){void* s = select;return 0;}" || quit
	define "HAS_SELECT"
	log_raw "Checking if AF_INET exists: "
	test_c "#include <winsock2.h>\nint main(int argc, char** argv){(void)AF_INET;return 0;}" || quit
else
	log_raw "Is this Linux build: "
	if test_c "#ifndef __linux__\n#error no\n#endif"; then
		CFLAGS="$CFLAGS -D_DEFAULT_SOURCE"
	fi
	log_raw "Checking if select exists: "
	if test_c "#include <sys/select.h>\nint main(int argc, char** argv){void* s = select;return 0;}"; then
		define "HAS_SELECT"
	fi
	log_raw "Checking if poll exists: "
	if test_c "#include <sys/poll.h>\nint main(int argc, char** argv){void* s = poll;return 0;}"; then
		define "HAS_POLL"
	fi
	log_raw "Checking if AF_INET exists: "
	test_c "#include <sys/socket.h>\nint main(int argc, char** argv){(void)AF_INET;return 0;}" || quit
fi

log_raw "Checking if strdup exists: "
if test_c "#include <string.h>\nint main(int argc, char** argv){void* s = strdup;return 0;}"; then
	define "HAS_STRDUP"
fi

while [ ! "x$OPENSSL" = "xno" -a ! "x$OPENSSL" = "xyes" -a ! "x$OPENSSL" = "xn" -a ! "x$OPENSSL" = "xy" ]; do
	getinput "Do you want an OpenSSL" "y"
	OPENSSL="`echo "$input" | tr '[:upper:]' '[:lower:]'`"
done

if [ "x$OPENSSL" = "xyes" ]; then
	OPENSSL="y"
elif [ "x$OPENSSL" = "xno" ]; then
	OPENSSL="n"
fi

if [ "$OPENSSL" = "y" ]; then
	log_raw "Checking if OpenSSL works: "
	test_c "#include <openssl/ssl.h>\nint main(int argc, char** argv){void* s = SSL_CTX_new;return 0;}" "-lcrypto -lssl" || quit
	define "HAS_OPENSSL"
fi

log_raw "Checking if openlog exists: "
if test_c "#include <syslog.h>\nint main(int argc, char** argv){void* s = openlog;return 0;}"; then
	define "HAS_SYSLOG"
	log_raw "Checking if LOG_PID exists: "
	if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_PID;return 0;}"; then
		define "HAS_LOG_PID"
	fi
	log_raw "Checking if LOG_PERROR exists: "
	if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_PERROR;return 0;}"; then
		define "HAS_LOG_PERROR"
	fi
	log_raw "Checking if LOG_NEWS exists: "
	if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_NEWS;return 0;}"; then
		define "HAS_LOG_NEWS"
	else
		log_raw "Checking if LOG_USER exists: "
		if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_USER;return 0;}"; then
			define "HAS_LOG_USER"
		fi
	fi
	log_raw "Checking if LOG_INFO exists: "
	if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_INFO;return 0;}"; then
		define "HAS_LOG_INFO"
	fi
	log_raw "Checking if LOG_NOTICE exists: "
	if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_NOTICE;return 0;}"; then
		define "HAS_LOG_NOTICE"
	else
		log_raw "Checking if LOG_WARNING exists: "
		if test_c "#include <syslog.h>\nint main(int argc, char** argv){(void)LOG_WARNING;return 0;}"; then
			define "HAS_LOG_WARNING"
		fi
	fi
fi

log_raw "Checking if fork exists: "
if test_c "#include <unistd.h>\nint main(int argc, char** argv){void* s = fork;return 0;}"; then
	define "HAS_FORK"
fi

echo "#define DEFINES {$DEFINES}" >> config.h

echo "#endif" >> config.h

log_raw "Finding Yacc: "
if [ "x$YACC" = "x" ]; then
	for i in byacc bison yacc; do
		OLDIFS="$IFS"
		IFS=":"
	
		for j in $PATH; do
			if [ -f $j/$i ]; then
				YACC=$j/$i
				break
			fi
		done
	
		IFS="$OLDIFS"
		if [ ! "x$YACC" = "x" ]; then
			break
		fi
	done
fi
if [ "x$YACC" = "x" ]; then
	echo "not found"
	quit
fi
echo "$YACC"

log_raw "Should I force -y to Yacc: "
echo "%%" > /tmp/test.y
echo "a: 'a'" >> /tmp/test.y
echo "%%" >> /tmp/test.y
$YACC -y /tmp/test.y >/dev/null 2>&1
if [ "$?" = "0" ]; then
	echo "yes"
	YACC="$YACC -y"
else
	echo "no"
fi
rm -f y.tab.c /tmp/test.y

log_raw "Finding Lex: "
if [ "x$LEX" = "x" ]; then
	for i in flex lex; do
		OLDIFS="$IFS"
		IFS=":"
	
		for j in $PATH; do
			if [ -f $j/$i ]; then
				LEX=$j/$i
				break
			fi
		done
	
		IFS="$OLDIFS"
		if [ ! "x$LEX" = "x" ]; then
			break
		fi
	done
fi
if [ "x$LEX" = "x" ]; then
	echo "not found"
	quit
fi
echo "$LEX"

echo "# This file is auto-generated" > config.mk
echo "CC = $CC" >> config.mk
echo "CFLAGS = $CFLAGS -ansi -O2 -DNEWSDIST_VERSION=\\\"$VERSION\\\" -DPREFIX=\\\"$PREFIX\\\"" >> config.mk
echo "LDFLAGS = $LDFLAGS -O2" >> config.mk
echo "LIBS = $LIBS" >> config.mk
echo "TOPDIR = `pwd`" >> config.mk
echo "EXEC = $EXEC" >> config.mk
echo "YACC = $YACC" >> config.mk
echo "LEX = $LEX" >> config.mk

log ""
log "Configuration successful, now run \`make\'"
log ""

stty echo
