#!/bin/sh
# $Id$
mode=1
first=1
output=""
input=""
for i in $@; do
	if [ "$mode" = "1" ]; then
		mode=0
		continue
	fi
	if [ "$first" = "1" ]; then
		output="$i"
	else
		input="$input +$i"
	fi
	first=0
done
CMD="wlib -q -b -n -fo $output $input"
echo "$0: $CMD"
exec $CMD
